import './day-01/index.js';
import './day-02/index.js';
import './day-03/index.js';
import './day-04/index.js';
import './day-05/index.js';
import './day-06/index.js';
import './day-07/index.js';
import './day-08/index.js';
import './day-09/index.js';
